export enum Genre {
  POP = 'pop',
  RAP = 'rap',
  DANCE = 'dance',
  ELECTRONIC = 'electronic',
  ALTERNATIVE = 'alternative',
  INDIE = 'indie',
  ROCK = 'rock',
  CLASSICAL = 'classical',
  METAL = 'metal',
  MEDITATION = 'meditation',
  NATURE = 'nature',
  JAZZ = 'jazz',
  BLUES = 'blues',
  RNB = 'rnb',
  CHANSON = 'chanson',
  COUNTRY = 'country',
  PUNK = 'punk',
  REGGAE = 'reggae',
  ANIME = 'anime',
  KPOP = 'kpop',
  PODCAST = 'podcast',
}
