function initializePlank() {
    let plank = document.createElement("div");
    plank.addEventListener("click", function () {
        let player = document.getElementsByClassName("player__container")[0];
        if (player.style.display === "block") {
            player.style.display = "none";
            document.getElementsByClassName("player__container")[0].style.display = "none";
        } else {
            player.style.display = "block";
        }
        plank.style.display = "none";
    })
    let image = document.createElement("img");
    image.setAttribute("data-amplitude-song-info", "cover_art_url");
    let container = document.createElement("div");
    let songName = document.createElement("span");
    songName.setAttribute("data-amplitude-song-info", "name");
    songName.classList.add("song__name");
    let songArtist = document.createElement("span");
    songArtist.setAttribute("data-amplitude-song-info", "artist");
    songArtist.classList.add("song__artist");
    container.appendChild(songName);
    container.appendChild(songArtist);
    container.style.height = "50px";
    container.style.margin = "auto 0";
    plank.classList.add("playing");
    plank.appendChild(image);
    plank.appendChild(container);
    document.body.insertAdjacentElement('beforeend', plank);
}

function initializePlayer(songs) {
    initializePlank();
    let playerContainer = document.createElement("div");
    playerContainer.classList.add("player__container");
    let listScreen = document.createElement("div");
    listScreen.classList.add("list_screen");
    let listScreenHeader = document.createElement("div");
    listScreenHeader.classList.add("list_screen__header");
    listScreenHeader.classList.add("hide-playlist");
    listScreenHeader.innerText = "Hide playlist";
    let playerPlaylist = document.createElement("div");
    playerPlaylist.classList.add("player__playlist");
    playerPlaylist.classList.add("list");
    addSongsFromInit(songs, playerPlaylist);
    let listScreenFooter = document.createElement("div");
    listScreenFooter.classList.add("list_screen__footer");
    let listScreenMetaContainer = document.createElement("div");
    listScreenMetaContainer.classList.add("list_screen__meta_container");
    let songName = document.createElement("span");
    songName.setAttribute("data-amplitude-song-info", "name");
    songName.classList.add("song__name")
    listScreenMetaContainer.appendChild(songName);
    let songArtistContainer = document.createElement("div");
    songArtistContainer.classList.add("song__artist");
    let songArtist = document.createElement("span");
    songArtist.setAttribute("data-amplitude-song-info", "artist");
    songArtistContainer.appendChild(songArtist);
    listScreenMetaContainer.appendChild(songArtistContainer);
    let listControls = document.createElement("div");
    listControls.classList.add("list__controls");
    let listPrev = document.createElement("div");
    listPrev.classList.add("list__previous");
    listPrev.classList.add("amplitude-prev");
    let listPlay = document.createElement("div");
    listPlay.classList.add("list__play-pause");
    listPlay.classList.add("amplitude-play-pause");
    let listNext = document.createElement("div");
    listNext.classList.add("list__next");
    listNext.classList.add("amplitude-next");
    listControls.appendChild(listPrev);
    listControls.appendChild(listPlay);
    listControls.appendChild(listNext);
    listScreenFooter.appendChild(listScreenMetaContainer);
    listScreenFooter.appendChild(listControls);
    listScreen.appendChild(listScreenHeader);
    listScreen.appendChild(playerPlaylist);
    listScreen.appendChild(listScreenFooter);

    let playerScreen = document.createElement("div");
    playerScreen.classList.add("player__screen");
    let playerScreenHeader = document.createElement("div");
    playerScreenHeader.classList.add("player__header");
    playerScreenHeader.classList.add("down-header");
    playerScreenHeader.innerText = "Show Playlist";
    playerScreen.appendChild(playerScreenHeader);
    let playerTop = document.createElement("div");
    playerTop.classList.add("player__top");
    let image = document.createElement("img");
    image.setAttribute("data-amplitude-song-info", "cover_art_url");
    playerTop.appendChild(image);
    playerScreen.appendChild(playerTop);
    let playerProgressBarContainer = document.createElement("div");
    playerProgressBarContainer.classList.add("player__progress_bar__container");
    let songProgress = document.createElement("progress");
    songProgress.classList.add("song__played__progress");
    songProgress.classList.add("amplitude-song-played-progress");
    let bufferProgress = document.createElement("progress");
    bufferProgress.classList.add("song__buffered__progress");
    bufferProgress.classList.add("amplitude-buffered-progress");
    bufferProgress.setAttribute("value", "0");
    playerProgressBarContainer.appendChild(songProgress);
    playerProgressBarContainer.appendChild(bufferProgress);
    playerScreen.appendChild(playerProgressBarContainer);
    let playerMiddle = document.createElement("div");
    playerMiddle.classList.add("player__middle");
    let timeContainer = document.createElement("div");
    timeContainer.classList.add("time__container");
    let currentTime = document.createElement("span");
    currentTime.classList.add("amplitude-current-time");
    let durationTime = document.createElement("span");
    durationTime.classList.add("amplitude-duration-time");
    timeContainer.appendChild(currentTime);
    timeContainer.appendChild(durationTime);
    playerMiddle.appendChild(timeContainer);
    let metaContainer = document.createElement("div");
    metaContainer.classList.add("meta__container");
    let playerSongName = document.createElement("span");
    playerSongName.classList.add("song__name");
    playerSongName.setAttribute("data-amplitude-song-info", "name");
    let playerSongArtistContainer = document.createElement("div");
    playerSongArtistContainer.classList.add("song__artist");
    let playerSongArtist = document.createElement("span");
    playerSongArtist.setAttribute("data-amplitude-song-info", "artist");
    playerSongArtistContainer.appendChild(playerSongArtist);
    metaContainer.appendChild(playerSongName);
    metaContainer.appendChild(playerSongArtistContainer);
    playerMiddle.appendChild(metaContainer);
    playerScreen.appendChild(playerMiddle);
    let playerBottom = document.createElement("div");
    playerBottom.classList.add("player__bottom");
    let controlContainer = document.createElement("div");
    controlContainer.classList.add("control_container");
    let prevContainer = document.createElement("div");
    prevContainer.classList.add("prev_container");
    let prev = document.createElement("div");
    prev.classList.add("amplitude-prev");
    prev.classList.add("previous");
    prevContainer.appendChild(prev);
    let playContainer = document.createElement("div");
    playContainer.classList.add("play-pause__container");
    let play = document.createElement("div");
    play.classList.add("amplitude-play-pause");
    play.classList.add("play-pause");
    playContainer.appendChild(play);
    let nextContainer = document.createElement("div");
    nextContainer.classList.add("next__container");
    let next = document.createElement("div");
    next.classList.add("amplitude-next");
    next.classList.add("next");
    nextContainer.appendChild(next);
    controlContainer.appendChild(prevContainer);
    controlContainer.appendChild(playContainer);
    controlContainer.appendChild(nextContainer);
    playerBottom.appendChild(controlContainer);
    let volumeContainer = document.createElement("div");
    volumeContainer.classList.add("volume__container");
    let vlmImage = document.createElement("img");
    vlmImage.setAttribute("src", "img/volume.svg");
    let input = document.createElement("input");
    input.classList.add("amplitude-volume-slider");
    input.setAttribute("type", "range");
    input.setAttribute("step", ".1");
    volumeContainer.appendChild(vlmImage);
    volumeContainer.appendChild(input);
    playerBottom.appendChild(volumeContainer);
    playerScreen.appendChild(playerBottom);

    playerContainer.appendChild(listScreen);
    playerContainer.appendChild(playerScreen);
    return playerContainer;
}

function addSongsFromInit(songs, playerPlaylist) {
    for (let i = 0; i < songs.length; i++) {
        let playlistItem = document.createElement("div");
        playlistItem.classList.add("song");
        playlistItem.classList.add("amplitude-song-container");
        playlistItem.classList.add("amplitude-play-pause");
        playlistItem.setAttribute("data-amplitude-song-index", i.toString());
        let number = document.createElement("span");
        number.classList.add("song_number__now_playing");
        number.innerText = (i + 1).toString();
        let songContainer = document.createElement("div");
        songContainer.classList.add("song__meta__container");
        let songName = document.createElement("span");
        songName.classList.add("song__name");
        songName.setAttribute("data-amplitude-song-info", "name");
        songName.setAttribute("data-amplitude-song-index", i.toString());
        let songArtist = document.createElement("span");
        songArtist.classList.add("song__artist");
        songArtist.setAttribute("data-amplitude-song-info", "artist");
        songArtist.setAttribute("data-amplitude-song-index", i.toString());
        let songDuration = document.createElement("span");
        songDuration.classList.add("song__duration");
        songDuration.setAttribute("data-amplitude-song-info", "duration");
        songDuration.setAttribute("data-amplitude-song-index", i.toString());
        songContainer.appendChild(songName);
        songContainer.appendChild(songArtist);
        playlistItem.appendChild(number);
        playlistItem.appendChild(songContainer);
        playlistItem.appendChild(songDuration);
        playerPlaylist.appendChild(playlistItem);
    }
}